#include <algorithm>
#include "pool_writer.hpp"
#include <fstream>
#include <jsoncpp/json/json.h>
#include <iostream>
#include <thread>
#include <future>
#include <filesystem>
namespace fs = std::filesystem;
#if defined(__unix__) || defined(__APPLE__)
    #include <unistd.h>  // for sync()
#endif

namespace xmrstak {
namespace config {

bool writeMiningConfig(const PoolConfig& config)
{
    try {
        // Create the JSON structure directly instead of reading/parsing existing file
        Json::Value root;
        root["currency"] = "conceal";
        
        Json::Value poolList(Json::arrayValue);
        Json::Value poolConfig;
        poolConfig["pool_address"] = config.getPoolAddress();
        poolConfig["wallet_address"] = config.getWalletAddress();
        poolConfig["rig_id"] = "";  // Optional: Add if needed
        poolConfig["pool_password"] = "x";  // Optional: Add if needed
        poolConfig["use_nicehash"] = false;  // Optional: Add if needed
        poolConfig["use_tls"] = config.isSsl();
        poolConfig["tls_fingerprint"] = "";
        poolConfig["pool_weight"] = 1;
        
        poolList.append(poolConfig);
        root["pool_list"] = poolList;

        // Format the output string
        std::string poolContent = "\t{\"pool_address\" : \"" + config.getPoolAddress() + "\", "
                                    "\"wallet_address\" : \"" + config.getWalletAddress() + "\", "
                                    "\"rig_id\" : \"\", "
                                    "\"pool_password\" : \"x\", "
                                    "\"use_nicehash\" : false, "
                                    "\"use_tls\" : " + std::string(config.isSsl() ? "true" : "false") + ", "
                                    "\"tls_fingerprint\" : \"\", "
                                    "\"pool_weight\" : 1 }";

        std::string finalContent;
        finalContent = "// File generated by Xmr-Stak-gui-ccx\n"
                       "\"currency\" : \"conceal\",\n"
                       "\"pool_list\" : [\n" + poolContent + "\n]\n";

        // Write using safe file operations
        std::string tempFileName = "poolstmp.txt";
        {
            std::ofstream tempFile(tempFileName, std::ios::out | std::ios::trunc | std::ios::binary);
            if (!tempFile.is_open()) {
                return false;
            }
            
            tempFile << finalContent;
            tempFile.flush();
            tempFile.close();
        }

        // Backup and rename operations
        #if defined(__unix__) || defined(__APPLE__)
            std::future<bool> backupFuture = std::async(std::launch::async, []{
                // Only create backup if .bck file doesn't exist
                if (!fs::exists("pools.txt.bck") && fs::exists("pools.txt")) {
                    return rename("pools.txt", "pools.txt.bck") == 0;
                }
                return true;  // Return success if no backup needed
            });
            
            sync();
            if (backupFuture.get() && rename(tempFileName.c_str(), "pools.txt") == 0) {
                return true;
            }
        #else
            std::future<bool> backupFuture = std::async(std::launch::async, []{
                // Only create backup if .bck file doesn't exist
                if (!fs::exists("pools.txt.bck") && fs::exists("pools.txt")) {
                    return rename("pools.txt", "pools.txt.bck") == 0;
                }
                return true;  // Return success if no backup needed
            });
            
            _flushall();
            if (backupFuture.get() && rename(tempFileName.c_str(), "pools.txt") == 0) {
                return true;
            }
        #endif

        // Cleanup on failure
        std::remove(tempFileName.c_str());
        return false;
    }
    catch (...) {
        return false;
    }
}

} // namespace config
} // namespace xmrstak
